version: '3.9'

volumes:
    dbdata:

services:

    api:
        restart: always
        image: thomasbinder/sea_animals_api:0.1
        container_name: api_functional_api
        ports:
            - "8081:8081"
        environment:
            - MODEL_PREDICT_ROUTE=${MODEL_PREDICT_ROUTE}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_CONNECTION=${MYSQL_CONNECTION}
            - API_KEY=${API_KEY}
            - API_KEY_NAME=${API_KEY_NAME}
        depends_on:
            - db
        links:
            - "db:mysql_database"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db:
        restart: always
        image: mysql:5.7
        container_name: api_functional_db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql