apiVersion: apps/v1
kind: Deployment
metadata:
  name: sea-animals-api-deployment
  labels:
    app: sea-animals-api-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sea-animals-api-app
  template:
    metadata:
      labels:
        app: sea-animals-api-app
    spec:
      containers:
      - name: api
        image: thomasbinder/sea_animals_api:0.1
        ports:
        - containerPort: 8000