name: training_pipeline
steps:
  load_data:
    source:
      name: image_data_loader
    parameters:
      test_size: 0.2
      data_path: './data'
      seed: 42
  train_model:
    source:
      name: train_classifier
    parameters:
      validation_split: 0.2
      input_shape: [224, 224, 3]
      dense_layers: [256, 256, 19]
      dropout_layers: [0.2, 0.2]
      batch_size: 4
      adam_param: 0.00001
      metrics: ["accuracy"]
      loss: "categorical_crossentropy"
      nb_epochs: 2
      seed: 42
  evaluate_model:
    source:
      name: evaluate_classifier