name: training_kubeflow_pipeline
steps:
  load_data:
    source:
      name: train_data_loader
      file: src/domain/steps/data_loader.py
    parameters:
      test_size: 0.2
      data_path: './data'
      seed: 42
  skew_detector:
    source:
      name: evidently_skew_detector
    parameters:
      step_name: "evidently_skew_detector"
      ignored_cols: ["Filepath"]
      profile_sections: ["datadrift"]
  train_model:
    source:
      name: train_classifier
      file: src/domain/steps/trainer.py
    parameters:
      validation_split: 0.2
      input_shape: [224, 224, 3]
      dense_layers: [256, 256, 19]
      dropout_layers: [0.2, 0.2]
      batch_size: 4
      adam_param: 0.00001
      metrics: ["accuracy"]
      loss: "categorical_crossentropy"
      nb_epochs: 2
      seed: 42
  evaluate_model:
    source:
      name: evaluate_classifier
      file: src/domain/steps/evaluator.py
    parameters:
      input_shape: [224, 224, 3]
      batch_size: 4
  deployment_trigger:
    source:
      name: deployment_trigger
      file: src/domain/steps/deployment_trigger.py
    parameters:
      seiling: 0.5