name: train_continuous_deployment_pipeline
steps:
  load_data:
    source:
      name: train_data_loader
      file: src/domain/steps/data_loader.py
    parameters:
      test_size: 0.2
      data_path: './data'
      seed: 42
  skew_detector:
    source:
      name: evidently_skew_detector
    parameters:
      step_name: "evidently_skew_detector"
      ignored_cols: ["Filepath"]
      profile_sections: ["datadrift"]
  train_model:
    source:
      name: train_classifier
      file: src/domain/steps/mlflow_trainer.py
    parameters:
      validation_split: 0.2
      input_shape: [224, 224, 3]
      dense_layers: [256, 256, 19]
      dropout_layers: [0.2, 0.2]
      batch_size: 16
      adam_param: 0.00001
      metrics: ["accuracy"]
      loss: "categorical_crossentropy"
      nb_epochs: 20
      seed: 42
      allow_gpu: True
      memory_limit: 6144
  evaluate_model:
    source:
      name: evaluate_classifier
      file: src/domain/steps/mlflow_evaluator.py
    parameters:
      input_shape: [224, 224, 3]
      batch_size: 4
  deployment_trigger:
    source:
      name: deployment_trigger
      file: src/domain/steps/deployment_trigger.py
    parameters:
      seiling: 0.8
  model_deployer:
    source:
      name: mlflow_model_deployer_step