name: staging_api

on:
  pull_request:
    branches:
      - "master"

jobs:
  build_test_api:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sea_animals_api:1.0 .
      -
        name: Test
        run: cd ./tests_integration/ && ./start.sh